#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
whonews — the day's headlines, read out loud by a character.

Pulls the top stories from Google News RSS and, 70% of the time (by default),
asks an AI backend for a short opinion in the character's voice about one of
them picked at random; 10% of the time the character skips the news and just
cracks a sarcastic joke; 10% it invents a brief anecdote with up to two other
random characters; and the remaining 10%, it just drops its signature phrase.
Either way, prints one panel through whosay. --joke-chance, --anecdote-chance
and --signature-chance change the split.

Ollama (local, free) is the default backend; --provider switches to
Anthropic or OpenAI, reading ANTHROPIC_API_KEY / OPENAI_API_KEY from the
environment.

This is a parody: the opinions are generated by a language model, not real
quotes from anyone.

Usage:
    whonews.py                          # one random take, Chile, medium portrait
    whonews.py -n 10 -b                 # pick from a bigger pool, big portrait
    whonews.py -C some_character        # a different character's take
    whonews.py --random                 # a random character's take
    whonews.py --topic WORLD            # a Google News section
    whonews.py --query "inteligencia artificial"
    whonews.py --headlines              # no model, just one random headline
    whonews.py --model gemma4:latest    # sharper takes, far slower
    whonews.py --refresh                # ignore the cache, ask again

Feeds and opinions are cached in SQLite (~/.cache/whosay/news.db), so a
second run costs nothing and the takes pile up into an archive. Takes older
than a week are dropped on the next run; --prune changes that.

Options:
    -n N              pool size to pick a headline from at random (default 5)
    -C, --character   which character comments (default carmen_gloria)
    --random          a random character comments
    --topic NAME      WORLD, NATION, BUSINESS, TECHNOLOGY, SCIENCE, SPORTS,
                      ENTERTAINMENT, HEALTH
    --query TEXT      search instead of browsing a section
                      (default: the character's "topic" field)
    --region CODE     country code for Google News
                      (default: from the character's "nationality", else CL)
    --lang CODE       language code
                      (default: from the character's "language", else es-419)
    --provider NAME   ollama, anthropic or openai
                      (default $WHONEWS_PROVIDER or ollama)
    --model NAME      model for the chosen provider
                      (default $WHONEWS_MODEL, else the provider's own
                      default: llama3.2:1b / claude-haiku-4-5-20251001 /
                      gpt-4o-mini)
    --headlines       skip the model, print the raw headlines
    --timeout SEC     per-request timeout for the model (default 120)
    --db PATH         cache location ($WHONEWS_DB overrides the default)
    --ttl MIN         how long a cached feed stays fresh (default 15)
    --refresh         re-fetch the feed and re-ask the model
    --no-cache        don't read or write the cache at all
    --history [N]     print the last N archived takes and exit
    --prune DAYS      drop takes older than DAYS (default 7, 0 keeps all)
    --joke-chance P   chance (0-1) of a standalone joke instead of a news
                      take (default 0.1)
    --anecdote-chance P
                      chance (0-1) the character tells a brief anecdote with
                      other characters instead (default 0.1)
    --signature-chance P
                      chance (0-1) the character just drops its signature
                      phrase instead (default 0.1)
    --signature       always print the signature phrase and exit
    --anecdote [NAME ...]
                      always tell a brief anecdote and exit; optionally list
                      which characters star in it (default: up to two random)
    plus every whosay look flag: -s/-m/-b, -c/-a/-W
"""
import argparse
import html
import json
import os
import random
import re
import sqlite3
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET

# Works when whonews is reached through a symlink in ~/.local/bin too.
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
import whosay  # noqa: E402

__version__ = "1.0"

SECTIONS = ("WORLD", "NATION", "BUSINESS", "TECHNOLOGY", "SCIENCE", "SPORTS",
            "ENTERTAINMENT", "HEALTH")

# Maps a character.json "nationality"/"language" value to the Google News
# region/lang code it implies. Add an entry here when a new character's
# nationality or language isn't one of these yet.
NATIONALITY_REGION = {
    "Chilean": "CL",
    "Argentine": "AR",
    "Mexican": "MX",
    "Peruvian": "PE",
    "Colombian": "CO",
    "Spanish": "ES",
    "American": "US",
    "British": "GB",
}
LANGUAGE_CODE = {
    "Spanish": "es-419",
    "English": "en-US",
    "Portuguese": "pt-BR",
}

# Header line printed before the headline/joke/anecdote/signature, in the
# character's language. (news_label, joke_label, anecdote_label, signature_label),
# each formatted with the character's display name.
LABELS = {
    "Spanish": ("Noticias con {}", "Chiste con {}", "Anécdota con {}", "La frase de {}"),
    "English": ("News with {}", "Joke with {}", "Anecdote with {}", "The catchphrase of {}"),
    "Portuguese": ("Notícias com {}", "Piada com {}", "Anedota com {}", "A frase de {}"),
}


# ------------------------------------------------------------------ character


def load_character(name):
    path = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                         "characters", name, "character.json")
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except OSError:
        available = ", ".join(whosay.list_characters()) or "none found"
        raise whosay.CharacterNotFound(
            "unknown character '{}' (available: {})".format(name, available))


# ------------------------------------------------------------------ cache
#
# Inline rather than a schema.sql file: one less loose file to find (and
# bundle) when whonews.py is symlinked or frozen into a standalone binary.
#
# feeds — the raw RSS body per URL, reused for --ttl minutes and pruned
#         after a day (FEED_KEEP below). Shared by every character, since
#         headlines don't depend on who's commenting on them.
# takes — one opinion per (headline, model, character), kept for
#         --prune days (TAKE_KEEP_DAYS below). Replaying a stored take
#         costs milliseconds instead of a model call.
SCHEMA = """
CREATE TABLE IF NOT EXISTS feeds (
    url        TEXT PRIMARY KEY,
    fetched_at REAL NOT NULL,
    body       BLOB NOT NULL
);
CREATE TABLE IF NOT EXISTS takes (
    headline   TEXT NOT NULL,
    model      TEXT NOT NULL,
    character  TEXT NOT NULL,
    source     TEXT,
    take       TEXT NOT NULL,
    created_at REAL NOT NULL,
    PRIMARY KEY (headline, model, character)
);
CREATE INDEX IF NOT EXISTS takes_by_date ON takes (created_at DESC);
"""

FEED_KEEP = 24 * 3600  # cached feed bodies are worthless after a day
TAKE_KEEP_DAYS = 7   # the archive is small, but not immortal
JOKE_CHANCE = 0.1    # how often the character skips the news for a joke instead
ANECDOTE_CHANCE = 0.1   # how often the character tells an anecdote with others instead
SIGNATURE_CHANCE = 0.1  # how often the character just drops its signature phrase


def default_db():
    env = os.environ.get("WHONEWS_DB")
    if env:
        return env
    base = os.environ.get("XDG_CACHE_HOME") or os.path.join(
        os.path.expanduser("~"), ".cache")
    return os.path.join(base, "whosay", "news.db")


def open_cache(path, prune_days=TAKE_KEEP_DAYS):
    """Open (and create) the cache. Returns None if the disk says no."""
    try:
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        db = sqlite3.connect(path, timeout=5)
        db.executescript(SCHEMA)
        db.execute("DELETE FROM feeds WHERE fetched_at < ?", (time.time() - FEED_KEEP,))
        dropped = prune(db, prune_days)
        db.commit()
        if dropped:
            print("whonews: pruned {} take{} older than {:g} days".format(
                dropped, "" if dropped == 1 else "s", prune_days), file=sys.stderr)
        return db
    except (sqlite3.Error, OSError) as e:
        print("whonews: cache disabled ({})".format(e), file=sys.stderr)
        return None


def prune(db, days):
    """Drop takes older than `days`. 0 (or less) keeps everything."""
    if db is None or days <= 0:
        return 0
    cur = db.execute("DELETE FROM takes WHERE created_at < ?",
                     (time.time() - days * 86400,))
    return cur.rowcount


def cached_feed(db, url, ttl):
    if db is None or ttl <= 0:
        return None
    row = db.execute(
        "SELECT body FROM feeds WHERE url = ? AND fetched_at > ?",
        (url, time.time() - ttl),
    ).fetchone()
    return row[0] if row else None


def store_feed(db, url, body):
    if db is None:
        return
    db.execute("INSERT OR REPLACE INTO feeds (url, fetched_at, body) VALUES (?, ?, ?)",
               (url, time.time(), body))
    db.commit()


def cached_take(db, headline, model, character):
    if db is None:
        return None
    row = db.execute(
        "SELECT take FROM takes WHERE headline = ? AND model = ? AND character = ?",
        (headline, model, character)).fetchone()
    return row[0] if row else None


def store_take(db, headline, model, character, source, take):
    if db is None:
        return
    db.execute(
        "INSERT OR REPLACE INTO takes (headline, model, character, source, take, created_at) "
        "VALUES (?, ?, ?, ?, ?, ?)",
        (headline, model, character, source, take, time.time()),
    )
    db.commit()


def history(db, limit, character):
    if db is None:
        return []
    return db.execute(
        "SELECT headline, source, take, created_at FROM takes "
        "WHERE character = ? ORDER BY created_at DESC LIMIT ?",
        (character, limit)).fetchall()


# ------------------------------------------------------------------ news


def news_url(topic=None, query=None, region="CL", lang="es-419"):
    tail = urllib.parse.urlencode({"hl": lang, "gl": region,
                                   "ceid": "{}:{}".format(region, lang.split("-")[0])})
    if query:
        q = urllib.parse.quote(query)
        return "https://news.google.com/rss/search?q={}&{}".format(q, tail)
    if topic:
        return "https://news.google.com/rss/headlines/section/topic/{}?{}".format(
            topic.upper(), tail)
    return "https://news.google.com/rss?{}".format(tail)


def feed_body(url, db, ttl):
    """The feed's raw XML, from cache when it's still fresh."""
    body = cached_feed(db, url, ttl)
    if body is not None:
        return body
    req = urllib.request.Request(url, headers={"User-Agent": "whonews/1.0"})
    with urllib.request.urlopen(req, timeout=20) as r:
        body = r.read()
    store_feed(db, url, body)
    return body


def parse_headlines(raw, count):
    """Return [(headline, source), ...] from a Google News RSS body."""
    root = ET.fromstring(raw)
    out, seen = [], set()
    for item in root.iter("item"):
        title = (item.findtext("title") or "").strip()
        if not title:
            continue
        title = html.unescape(title)
        src = item.find("source")
        source = (src.text or "").strip() if src is not None else ""
        # Google appends " - Outlet" to the title; drop it, we show it apart.
        if source and title.endswith(" - " + source):
            title = title[: -len(source) - 3].strip()
        title = re.sub(r"\s+", " ", title)
        key = title.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append((title, source))
        if len(out) >= count:
            break
    return out


# ------------------------------------------------------------------ model
#
# Each provider is a call(persona, prompt, model, timeout) -> raw text
# function. Add a new one here (plus its default model in DEFAULT_MODELS)
# to support another backend.


def ollama_host():
    host = os.environ.get("OLLAMA_HOST", "127.0.0.1:11434")
    if not host.startswith("http"):
        host = "http://" + host
    return host.rstrip("/")


def _post_json(url, body, timeout, headers=None):
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(),
        headers=dict(headers or {}, **{"Content-Type": "application/json"}),
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def _call_ollama(persona, prompt, model, timeout):
    body = {
        "model": model,
        "system": persona,
        "prompt": prompt,
        "stream": False,
        # Reasoning models burn the whole budget thinking and answer nothing.
        "think": False,
        "options": {"temperature": 0.9, "top_p": 0.95, "num_predict": 200},
    }
    url = ollama_host() + "/api/generate"
    try:
        data = _post_json(url, body, timeout)
    except urllib.error.HTTPError as e:
        if e.code != 400:
            raise
        body.pop("think")  # older Ollama, or a model that rejects the flag
        body["options"]["num_predict"] = 600
        data = _post_json(url, body, timeout)
    return data.get("response", "")


def _call_anthropic(persona, prompt, model, timeout):
    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        raise RuntimeError("ANTHROPIC_API_KEY is not set")
    body = {
        "model": model,
        "system": persona,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 200,
        "temperature": 0.9,
    }
    data = _post_json(
        "https://api.anthropic.com/v1/messages", body, timeout,
        headers={"x-api-key": key, "anthropic-version": "2023-06-01"},
    )
    return "".join(p.get("text", "") for p in data.get("content", []))


def _call_openai(persona, prompt, model, timeout):
    key = os.environ.get("OPENAI_API_KEY")
    if not key:
        raise RuntimeError("OPENAI_API_KEY is not set")
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": persona},
            {"role": "user", "content": prompt},
        ],
        "max_tokens": 200,
        "temperature": 0.9,
    }
    data = _post_json(
        "https://api.openai.com/v1/chat/completions", body, timeout,
        headers={"Authorization": "Bearer " + key},
    )
    return data["choices"][0]["message"]["content"]


PROVIDERS = {
    "ollama": _call_ollama,
    "anthropic": _call_anthropic,
    "openai": _call_openai,
}

DEFAULT_MODELS = {
    "ollama": "llama3.2:1b",
    "anthropic": "claude-haiku-4-5-20251001",
    "openai": "gpt-4o-mini",
}


def model_error(provider, e):
    if provider == "ollama":
        return ("whonews: no answer from Ollama at {} ({}). "
                 "Is `ollama serve` running?".format(ollama_host(), e))
    return "whonews: no answer from {} ({})".format(provider, e)


def ask_character(persona, prompt, provider, model, timeout, display_name):
    """Ask the configured provider for something in the character's voice.

    Returns a single line."""
    answer = PROVIDERS[provider](persona, prompt, model, timeout)
    return clean(answer, display_name)


def opine(persona, headline, provider, model, timeout, display_name):
    return ask_character(persona, "Titular: {}".format(headline),
                         provider, model, timeout, display_name)


def joke(persona, joke_prompt, provider, model, timeout, display_name):
    return ask_character(persona, joke_prompt, provider, model, timeout, display_name)


def anecdote(persona, others, provider, model, timeout, display_name):
    """Ask the configured provider for a brief anecdote in the character's own
    voice, starring it alongside the given other characters. One line."""
    prompt = (
        "Inventa una anécdota breve, en tu propio estilo, en la que tú y {}\n"
        "sean los protagonistas.\n"
        "Make up a brief anecdote, in your own style, in which you and {}\n"
        "are the protagonists."
    ).format(others, others)
    return ask_character(persona, prompt, provider, model, timeout, display_name)


def anecdote_cast(requested, character, lang):
    """Resolve the 'A, B and C' cast string for an anecdote prompt.

    requested is a list of character folder names, or empty to pick up to two
    random others. Returns None if no cast could be resolved."""
    if requested:
        names = []
        for name in requested:
            try:
                names.append(load_character(name).get("display_name", name))
            except whosay.CharacterNotFound:
                print("whonews: unknown character '{}'".format(name), file=sys.stderr)
        if not names:
            return None
    else:
        others = [c for c in whosay.list_characters() if c != character]
        if not others:
            return None
        subjects = random.sample(others, min(2, len(others)))
        names = []
        for s in subjects:
            try:
                names.append(load_character(s).get("display_name", s))
            except whosay.CharacterNotFound:
                names.append(s)
    conj = {"English": " and ", "Portuguese": " e "}.get(lang, " y ")
    return conj.join(names)


GENERIC_LABEL = r"opini[oó]n|respuesta"


def clean(text, display_name):
    """Small models like to pad; keep the first real sentence-ish line."""
    # Models sometimes echo the character's name, or a generic label, before
    # the actual line ("Carmen Gloria: ...", "Opinión: ...") — strip it.
    label = r"{}|{}".format(re.escape(display_name), GENERIC_LABEL)
    line_re = re.compile(r"^\W*(?:{})\s*:?\W*$".format(label), re.I)
    prefix_re = re.compile(r"^(?:{})\s*:\s*".format(label), re.I)

    text = re.sub(r"<think>.*?</think>", "", text, flags=re.S | re.I)
    lines = [l.strip(" *_#").strip() for l in text.split("\n")]
    lines = [l for l in lines if l and not line_re.match(l)]
    text = lines[0] if lines else ""
    text = prefix_re.sub("", text)
    return text.strip().strip('"“”').strip()


# ------------------------------------------------------------------ output


def say(text, character, size, mode, width):
    """Print one whosay panel with a given character, portrait size and color mode."""
    for line in whosay.bubble(text, width):
        print(" " * INDENT[size] + line)
    print("\n".join(whosay.tail(False, INDENT[size])))
    print("\n".join(whosay.art(character, size, mode)))


INDENT = {"small": 1, "medium": 2, "big": 4}


def main(argv=None):
    p = argparse.ArgumentParser(
        prog="whonews",
        description="The day's headlines, with a character's opinion (parody).",
        epilog="example:\n"
               "  whonews -C ozzy -n 3\n"
               "  whonews --topic technology -a -b\n"
               "  whonews --anecdote carmen_gloria st_ignucius\n"
               "  whonews --history 10",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("-n", "--count", type=int, default=5, help="how many stories")
    p.add_argument("-C", "--character", default="carmen_gloria",
                   help="which character comments (default: carmen_gloria)")
    p.add_argument("--random", action="store_true",
                   help="pick a random character")
    p.add_argument("--topic", choices=[s.lower() for s in SECTIONS] + list(SECTIONS),
                   help="Google News section")
    p.add_argument("--query", help="search term instead of a section "
                   "(default: the character's favorite topic)")
    p.add_argument("--region", default=None,
                   help="country code for Google News "
                        "(default: from the character's nationality, else CL)")
    p.add_argument("--lang", default=None,
                   help="language code (default: from the character's "
                        "language, else es-419)")
    p.add_argument("--provider", choices=list(PROVIDERS),
                   default=os.environ.get("WHONEWS_PROVIDER", "ollama"),
                   help="AI backend: ollama, anthropic or openai "
                        "(default $WHONEWS_PROVIDER or ollama)")
    p.add_argument("--model", default=None,
                   help="model name (default: $WHONEWS_MODEL, else the "
                        "provider's own default)")
    p.add_argument("--headlines", action="store_true", help="skip the model")
    p.add_argument("--timeout", type=float, default=120, help="model timeout (s)")
    p.add_argument("--db", default=default_db(), help="cache location")
    p.add_argument("--ttl", type=float, default=15, help="feed freshness (minutes)")
    p.add_argument("--refresh", action="store_true", help="re-fetch and re-ask")
    p.add_argument("--no-cache", action="store_true", help="ignore the cache entirely")
    p.add_argument("--history", nargs="?", type=int, const=10, metavar="N",
                   help="print the last N archived takes and exit")
    p.add_argument("--prune", type=float, default=TAKE_KEEP_DAYS, metavar="DAYS",
                   help="drop takes older than DAYS (default 365, 0 keeps all)")
    p.add_argument("--joke-chance", type=float, default=JOKE_CHANCE, metavar="P",
                   help="chance (0-1) of a standalone joke instead of a news "
                        "take (default {})".format(JOKE_CHANCE))
    p.add_argument("--anecdote-chance", type=float, default=ANECDOTE_CHANCE, metavar="P",
                   help="chance (0-1) the character tells a brief anecdote "
                        "with other characters instead (default {})".format(ANECDOTE_CHANCE))
    p.add_argument("--signature-chance", type=float, default=SIGNATURE_CHANCE, metavar="P",
                   help="chance (0-1) the character just drops its signature "
                        "phrase instead (default {})".format(SIGNATURE_CHANCE))
    p.add_argument("--signature", action="store_true",
                   help="always print the character's signature phrase and exit")
    p.add_argument("--anecdote", nargs="*", metavar="NAME",
                   help="always tell a brief anecdote and exit; optionally list "
                        "which characters star in it (default: up to two random)")
    g = p.add_mutually_exclusive_group()
    g.add_argument("-s", "--small", action="store_const", const="small", dest="size",
                   help="20-column portrait")
    g.add_argument("-m", "--medium", action="store_const", const="medium", dest="size",
                   help="40-column portrait (default)")
    g.add_argument("-b", "--big", action="store_const", const="big", dest="size",
                   help="60-column portrait")
    c = p.add_mutually_exclusive_group()
    c.add_argument("-c", "--color", action="store_const", const="block", dest="mode",
                   help="truecolor with block chars (photo-like)")
    c.add_argument("-a", "--ansi", action="store_const", const="ansi", dest="mode",
                   help="truecolor with ASCII chars")
    c.add_argument("--no-color", action="store_const", const="mono", dest="mode",
                   help="monochrome, classic ASCII")
    p.add_argument("-W", "--width", type=int, default=40, help="text width")
    p.add_argument("--version", action="version", version="whonews " + __version__)
    a = p.parse_args(argv)

    character = a.character
    if a.random:
        chars = whosay.list_characters()
        if not chars:
            print("whonews: no characters found in characters/", file=sys.stderr)
            return 1
        character = random.choice(chars)

    try:
        char = load_character(character)
    except whosay.CharacterNotFound as e:
        print("whonews: {}".format(e), file=sys.stderr)
        return 1
    persona = char["persona"]
    joke_prompt = char["joke_prompt"]
    display_name = char.get("display_name", character)
    fallback = char.get("fallback", "...")

    region = (a.region or os.environ.get("WHONEWS_REGION")
              or NATIONALITY_REGION.get(char.get("nationality"), "CL"))
    lang = (a.lang or os.environ.get("WHONEWS_LANG")
            or LANGUAGE_CODE.get(char.get("language"), "es-419"))
    query = a.query
    if not a.topic and not query:
        query = char.get("topic")
    news_label, joke_label, anecdote_label, signature_label = LABELS.get(char.get("language"), LABELS["Spanish"])
    signature = char.get("signature")
    model = a.model or os.environ.get("WHONEWS_MODEL") or DEFAULT_MODELS[a.provider]

    size = whosay.pick_size(a.size)
    mode = whosay.pick_mode(a.mode)
    db = None if a.no_cache else open_cache(a.db, a.prune)

    def title(text):
        print("\033[1m{}\033[0m".format(text) if mode != "mono" else text)

    def dated_title(stamp, text):
        if mode != "mono":
            print("\033[36m{}\033[0m  \033[1m{}\033[0m".format(stamp, text))
        else:
            print("{}  {}".format(stamp, text))

    if a.signature:
        if not signature:
            print("whonews: '{}' has no signature phrase".format(display_name),
                  file=sys.stderr)
            return 1
        title(signature_label.format(display_name))
        say(signature, character, size, mode, a.width)
        return 0

    if a.anecdote is not None:
        cast = anecdote_cast(a.anecdote, character, char.get("language"))
        if not cast:
            print("whonews: no characters to tell an anecdote with", file=sys.stderr)
            return 1
        title(anecdote_label.format(display_name))
        try:
            take = anecdote(persona, cast, a.provider, model, a.timeout, display_name)
        except RuntimeError as e:
            print("whonews: {}".format(e), file=sys.stderr)
            return 1
        except urllib.error.URLError as e:
            print(model_error(a.provider, e), file=sys.stderr)
            return 1
        except OSError as e:
            print("whonews: model error: {}".format(e), file=sys.stderr)
            return 1
        say(take or fallback, character, size, mode, a.width)
        return 0

    if a.history is not None:
        rows = history(db, a.history, character)
        if not rows:
            print("whonews: nothing archived yet", file=sys.stderr)
            return 1
        for headline, source, take, when in rows:
            stamp = time.strftime("%Y-%m-%d %H:%M", time.localtime(when))
            dated_title(stamp, "{}{}".format(headline,
                                             " ({})".format(source) if source else ""))
            say(take, character, size, mode, a.width)
            print()
        return 0

    url = news_url(a.topic, query, region, lang)
    ttl = 0 if a.refresh else a.ttl * 60
    try:
        stories = parse_headlines(feed_body(url, db, ttl), a.count)
    except (urllib.error.URLError, ET.ParseError, OSError) as e:
        print("whonews: could not read Google News: {}".format(e), file=sys.stderr)
        return 1
    if not stories:
        print("whonews: the feed came back empty", file=sys.stderr)
        return 1

    if a.headlines:
        title(news_label.format(display_name))
        headline, source = random.choice(stories)
        dated_title(time.strftime("%Y-%m-%d"),
                    "{}{}".format(headline, " ({})".format(source) if source else ""))
        return 0

    others = [c for c in whosay.list_characters() if c != character]
    if signature and random.random() < a.signature_chance:
        title(signature_label.format(display_name))
        say(signature, character, size, mode, a.width)
        return 0

    if others and random.random() < a.anecdote_chance:
        cast = anecdote_cast([], character, char.get("language"))
        title(anecdote_label.format(display_name))
        try:
            take = anecdote(persona, cast, a.provider, model, a.timeout, display_name)
        except RuntimeError as e:
            print("whonews: {}".format(e), file=sys.stderr)
            return 1
        except urllib.error.URLError as e:
            print(model_error(a.provider, e), file=sys.stderr)
            return 1
        except OSError as e:
            print("whonews: model error: {}".format(e), file=sys.stderr)
            return 1
        say(take or fallback, character, size, mode, a.width)
        return 0

    if random.random() < a.joke_chance:
        title(joke_label.format(display_name))
        try:
            take = joke(persona, joke_prompt, a.provider, model, a.timeout, display_name)
        except RuntimeError as e:
            print("whonews: {}".format(e), file=sys.stderr)
            return 1
        except urllib.error.URLError as e:
            print(model_error(a.provider, e), file=sys.stderr)
            return 1
        except OSError as e:
            print("whonews: model error: {}".format(e), file=sys.stderr)
            return 1
        say(take or fallback, character, size, mode, a.width)
        return 0

    title(news_label.format(display_name))
    headline, source = random.choice(stories)
    dated_title(time.strftime("%Y-%m-%d"),
                "{}{}".format(headline, " ({})".format(source) if source else ""))
    take = None if a.refresh else cached_take(db, headline, model, character)
    if take is None:
        try:
            take = opine(persona, headline, a.provider, model, a.timeout, display_name)
        except RuntimeError as e:
            print("whonews: {}".format(e), file=sys.stderr)
            return 1
        except urllib.error.URLError as e:
            print(model_error(a.provider, e), file=sys.stderr)
            return 1
        except OSError as e:
            print("whonews: model error: {}".format(e), file=sys.stderr)
            return 1
        if take:
            store_take(db, headline, model, character, source, take)
    say(take or fallback, character, size, mode, a.width)
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (BrokenPipeError, KeyboardInterrupt):
        pass
