#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
whonews — the day's headlines, read out loud by a character.

Pulls the top stories from Google News RSS and, 70% of the time (by default),
asks an AI backend for a short opinion in the character's voice about one of
them picked at random; 10% of the time the character skips the news and just
cracks a sarcastic joke; 10% it invents a brief anecdote with one other
random character; and the remaining 10%, it just drops its signature phrase.
Either way, prints one panel through whocast. --joke-chance, --anecdote-chance
and --signature-chance change the split.

A local llama.cpp server (free, no network) is the default backend.
--provider (or $WHONEWS_PROVIDER) switches to anthropic or openai, and
--anthropic-url / --openai-url point a provider at another endpoint (a
gateway, a proxy, a mock).

When the model doesn't answer at all — the local server is down, the key is
wrong, the network is out — the run still prints something: the character's
newest archived take, else its fallback line, else its signature phrase.

This is a parody: the opinions are generated by a language model, not real
quotes from anyone.

Usage:
    whonews.py                          # a random character's take, small portrait
    whonews.py -n 10 -b                 # pick from a bigger pool, big portrait
    whonews.py -C some_character        # always the same character's take
    whonews.py --topic WORLD            # a Google News section
    whonews.py --query "inteligencia artificial"
    whonews.py --headlines              # no model, just one random headline
    whonews.py --model gemma-3-4b       # sharper takes, far slower
    whonews.py --refresh                # ignore the cache, ask again

Feeds and opinions are cached in SQLite (~/.cache/whosay/news.db), so a
second run costs nothing and the takes pile up into an archive. A fetched
feed is reused for --ttl minutes (default a day) before being re-fetched,
and cached feed bodies are kept for a day regardless so a fetch that fails
(e.g. offline) can fall back to the last cached copy; with no cached copy
at all, the archive answers instead (see above). Takes older than a week are
dropped on the next run; --prune changes that.

Options:
    -n N              pool size to pick a headline from at random (default 5)
    -C, --character   which character comments (default: a random one)
    --random          a random character comments (the default)
    --topic NAME      WORLD, NATION, BUSINESS, TECHNOLOGY, SCIENCE, SPORTS,
                      ENTERTAINMENT, HEALTH
    --query TEXT      search instead of browsing a section
                      (default: the character's "topic" field)
    --region CODE     country code for Google News
                      (default: from the character's "nationality", else CL)
    --lang CODE       language code
                      (default: from the character's "language", else es-419)
    --provider NAME   ollama, anthropic or openai
                      (default $WHONEWS_PROVIDER, else ollama: the local
                      llama-server)
    --anthropic-key K anthropic credential (default $ANTHROPIC_API_KEY)
    --anthropic-url U anthropic base url
                      (default $ANTHROPIC_BASE_URL or https://api.anthropic.com)
    --openai-key K    openai credential (default $OPENAI_API_KEY)
    --openai-url U    openai base url
                      (default $OPENAI_BASE_URL or https://api.openai.com)
    --ollama-url U    local llama-server base url
                      (default $LLAMA_HOST or http://127.0.0.1:8080)
    --model NAME      model for the chosen provider
                      (default $WHONEWS_MODEL, else the provider's own
                      default: coder-3b / claude-haiku-4-5-20251001 /
                      gpt-4o-mini)
    --headlines       skip the model, print the raw headlines
    --timeout SEC     per-request timeout for the model (default 120)
    --db PATH         cache location ($WHONEWS_DB overrides the default)
    --ttl MIN         how long a cached feed stays fresh (default 1440 = 1 day)
    --refresh         re-fetch the feed and re-ask the model
    --no-cache        don't read or write the cache at all
    --history [N]     print the last N archived takes and exit (default 10)
    --prune DAYS      drop takes older than DAYS (default 7, 0 keeps all)
    --joke-chance P   chance (0-1) of a standalone joke instead of a news
                      take (default 0.1)
    --anecdote-chance P
                      chance (0-1) the character tells a brief anecdote with
                      another character instead (default 0.1)
    --signature-chance P
                      chance (0-1) the character just drops its signature
                      phrase instead (default 0.1)
    --signature       always print the signature phrase and exit
    --anecdote [NAME]
                      always tell a brief anecdote and exit; optionally give
                      which character stars in it (default: one random)
    --version         print the version and exit
    plus every whosay look flag: -s/-m/-b, -c/-a/--no-color, -W (they
                      live in whocast.py, shared by both scripts). -n is
                      --count here, so the mono flag goes by its long
                      name alone.
"""
import argparse
import html
import json
import os
import random
import re
import sqlite3
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from dataclasses import dataclass

# Works when whonews is reached through a symlink in ~/.local/bin too.
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
import whocast  # noqa: E402

__version__ = "1.0"

# ------------------------------------------------------------------ defaults
GOOGLE_NEWS_BASE_URL = "https://news.google.com/rss"
DEFAULT_COUNT = 5        # headline pool size to pick from
DEFAULT_REGION = "CL"    # Google News region, when the character has none
DEFAULT_LANG = "es-419"  # Google News language, when the character has none
DEFAULT_PROVIDER = "ollama"  # local and free, unless asked for another
DEFAULT_TIMEOUT = 120    # seconds, per model request
DEFAULT_HISTORY_N = 10   # --history with no count given
DEFAULT_TTL_MIN = 1440   # feed cache freshness, in minutes (1 day)
FEED_KEEP = 24 * 3600    # cached feed bodies are worthless after a day
TAKE_KEEP_DAYS = 7       # the archive is small, but not immortal
JOKE_CHANCE = 0.1        # how often the character skips the news for a joke instead
ANECDOTE_CHANCE = 0.1    # how often the character tells an anecdote with another instead
SIGNATURE_CHANCE = 0.1   # how often the character just drops its signature phrase
DEFAULT_MODELS = {
    # "coder-3b" matches this repo's local llama-server setup (a llama-swap
    # style router with several aliases) — override with --model/
    # $WHONEWS_MODEL for a single-model llama-server, or any other alias.
    "ollama": "coder-3b",
    "anthropic": "claude-haiku-4-5-20251001",
    "openai": "gpt-4o-mini",
}


@dataclass(frozen=True)
class ProviderPort:
    """ProviderPort Names where one backend's Key and base Url come from."""
    key_arg: str      # --<name>-key, None for a backend that needs no key
    key_env: str
    url_arg: str      # --<name>-url
    url_env: str
    default_url: str


# The command-line flag outranks the environment variable, which outranks
# the default. Add a backend here (plus its call in PROVIDERS and its model
# in DEFAULT_MODELS) to support another one.
PROVIDER_PORTS = {
    "ollama": ProviderPort(
        None, None, "ollama_url", "LLAMA_HOST", "http://127.0.0.1:8080"),
    "anthropic": ProviderPort(
        "anthropic_key", "ANTHROPIC_API_KEY",
        "anthropic_url", "ANTHROPIC_BASE_URL", "https://api.anthropic.com"),
    "openai": ProviderPort(
        "openai_key", "OPENAI_API_KEY",
        "openai_url", "OPENAI_BASE_URL", "https://api.openai.com"),
}

SECTIONS = ("WORLD", "NATION", "BUSINESS", "TECHNOLOGY", "SCIENCE", "SPORTS",
            "ENTERTAINMENT", "HEALTH")

# Maps a character.json "nationality"/"language" value to the Google News
# region/lang code it implies. Add an entry here when a new character's
# nationality or language isn't one of these yet.
NATIONALITY_REGION = {
    "Chilean": "CL",
    "Argentine": "AR",
    "Mexican": "MX",
    "Peruvian": "PE",
    "Colombian": "CO",
    "Spanish": "ES",
    "American": "US",
    "British": "GB",
}
LANGUAGE_CODE = {
    "Spanish": "es-419",
    "English": "en-US",
    "Portuguese": "pt-BR",
}

# Header line printed before the headline/joke/anecdote/signature, in the
# character's language. (news_label, joke_label, anecdote_label, signature_label),
# each formatted with the character's display name.
LABELS = {
    "Spanish": ("Noticias con {}", "Chiste con {}", "Anécdota con {}", "La frase de {}"),
    "English": ("News with {}", "Joke with {}", "Anecdote with {}", "The catchphrase of {}"),
    "Portuguese": ("Notícias com {}", "Piada com {}", "Anedota com {}", "A frase de {}"),
}


def main(argv=None):
    """Main Parses the Args,
       Resolves the Character and Session,
       then Runs the matching whonews Command."""
    args = parse_whonews_args(argv)

    try:
        character, char = resolve_requested_character(args)
    except whocast.CharacterNotFound as e:
        print("whonews: {}".format(e), file=sys.stderr)
        return 1

    session = build_news_session(character, char, args)

    if args.signature:
        return run_signature_command(session)
    if args.anecdote is not None:
        return run_anecdote_command(session, args.anecdote or None)
    if args.history is not None:
        return run_history_command(session, args.history)

    return run_news_command(session, args)


def parse_whonews_args(argv):
    """ParseWhonewsArgs Builds the Cli parser,
       Parses argv,
       then Fills in the Provider nobody asked for."""
    parser = argparse.ArgumentParser(
        prog="whonews",
        description="The day's headlines, with a character's opinion (parody).",
        epilog="example:\n"
               "  whonews -C ozzy -n 3\n"
               "  whonews --topic technology -a -b\n"
               "  whonews --anecdote carmen_gloria\n"
               "  whonews --history 10",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("-n", "--count", type=int, default=DEFAULT_COUNT, help="how many stories")
    chars = whocast.list_characters()
    whocast.add_character_arguments(parser, "which character comments (default: a random one)")
    parser.add_argument("--topic", choices=[s.lower() for s in SECTIONS] + list(SECTIONS),
                         help="Google News section")
    parser.add_argument("--query", help="search term instead of a section "
                         "(default: the character's favorite topic)")
    parser.add_argument("--region", default=None,
                         help="country code for Google News "
                              "(default: from the character's nationality, else {})".format(DEFAULT_REGION))
    parser.add_argument("--lang", default=None,
                         help="language code (default: from the character's "
                              "language, else {})".format(DEFAULT_LANG))
    parser.add_argument("--provider", choices=list(PROVIDERS), default=None,
                         help="AI backend: ollama, anthropic or openai "
                              "(default $WHONEWS_PROVIDER, else {}: the local "
                              "llama-server)".format(DEFAULT_PROVIDER))
    parser.add_argument("--anthropic-key", default=None, metavar="KEY",
                         help="anthropic credential (default $ANTHROPIC_API_KEY)")
    parser.add_argument("--anthropic-url", default=None, metavar="URL",
                         help="anthropic base url (default $ANTHROPIC_BASE_URL, else {})".format(
                             PROVIDER_PORTS["anthropic"].default_url))
    parser.add_argument("--openai-key", default=None, metavar="KEY",
                         help="openai credential (default $OPENAI_API_KEY)")
    parser.add_argument("--openai-url", default=None, metavar="URL",
                         help="openai base url (default $OPENAI_BASE_URL, else {})".format(
                             PROVIDER_PORTS["openai"].default_url))
    parser.add_argument("--ollama-url", default=None, metavar="URL",
                         help="local llama-server base url (default $LLAMA_HOST, else {})".format(
                             PROVIDER_PORTS["ollama"].default_url))
    parser.add_argument("--model", default=None,
                         help="model name (default: $WHONEWS_MODEL, else the "
                              "provider's own default)")
    parser.add_argument("--headlines", action="store_true", help="skip the model")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT, help="model timeout (s)")
    parser.add_argument("--db", default=resolve_db_path(), help="cache location")
    parser.add_argument("--ttl", type=float, default=DEFAULT_TTL_MIN,
                         help="feed freshness (minutes, default {} = 1 day)".format(DEFAULT_TTL_MIN))
    parser.add_argument("--refresh", action="store_true", help="re-fetch and re-ask")
    parser.add_argument("--no-cache", action="store_true", help="ignore the cache entirely")
    parser.add_argument("--history", nargs="?", type=int, const=DEFAULT_HISTORY_N, metavar="N",
                         help="print the last N archived takes and exit")
    parser.add_argument("--prune", type=float, default=TAKE_KEEP_DAYS, metavar="DAYS",
                         help="drop takes older than DAYS (default {}, 0 keeps all)".format(TAKE_KEEP_DAYS))
    parser.add_argument("--joke-chance", type=float, default=JOKE_CHANCE, metavar="P",
                         help="chance (0-1) of a standalone joke instead of a news "
                              "take (default {})".format(JOKE_CHANCE))
    parser.add_argument("--anecdote-chance", type=float, default=ANECDOTE_CHANCE, metavar="P",
                         help="chance (0-1) the character tells a brief anecdote "
                              "with another character instead (default {})".format(ANECDOTE_CHANCE))
    parser.add_argument("--signature-chance", type=float, default=SIGNATURE_CHANCE, metavar="P",
                         help="chance (0-1) the character just drops its signature "
                              "phrase instead (default {})".format(SIGNATURE_CHANCE))
    parser.add_argument("--signature", action="store_true",
                         help="always print the character's signature phrase and exit")
    parser.add_argument("--anecdote", nargs="?", const="", default=None, metavar="NAME",
                         choices=chars or None,
                         help="always tell a brief anecdote and exit; optionally give "
                              "which character stars in it (default: one random)")
    # -n is already --count here, so the mono flag goes by its long name alone.
    whocast.add_look_arguments(parser, mono_flags=("--no-color",))
    parser.add_argument("--version", action="version", version="whonews " + __version__)

    args = parser.parse_args(argv)
    args.provider = args.provider or resolve_default_provider(args)
    return args


def resolve_requested_character(args):
    """ResolveRequestedCharacter Picks the named Character,
       or a random one when nobody named it,
       then Returns it with its config."""
    character = whocast.pick_character(args.character, args.random)
    return character, whocast.load_character(character)


@dataclass
class NewsSession:
    """NewsSession Bundles one resolved Character's voice, cache handle and look Settings."""
    character: str
    persona: str
    joke_prompt: str
    display_name: str
    fallback: str
    signature: str
    region: str
    lang: str
    query: str
    news_label: str
    joke_label: str
    anecdote_label: str
    signature_label: str
    backend: object
    size: str
    mode: str
    width: int
    db: object


def build_news_session(character, char, args):
    """BuildNewsSession Resolves region/lang/labels/backend from the Character and Args,
       then Returns a Session."""
    region = (args.region or os.environ.get("WHONEWS_REGION")
              or NATIONALITY_REGION.get(char.get("nationality"), DEFAULT_REGION))
    lang = (args.lang or os.environ.get("WHONEWS_LANG")
            or LANGUAGE_CODE.get(char.get("language"), DEFAULT_LANG))
    query = args.query
    if not args.topic and not query:
        query = char.get("topic")
    news_label, joke_label, anecdote_label, signature_label = LABELS.get(
        char.get("language"), LABELS["Spanish"])
    db = None if args.no_cache else open_news_cache(args.db, args.prune)

    return NewsSession(
        character=character,
        persona=char["persona"],
        joke_prompt=char["joke_prompt"],
        display_name=char.get("display_name", character),
        fallback=char.get("fallback") or char.get("signature") or "...",
        signature=char.get("signature"),
        region=region,
        lang=lang,
        query=query,
        news_label=news_label,
        joke_label=joke_label,
        anecdote_label=anecdote_label,
        signature_label=signature_label,
        backend=build_model_backend(args),
        size=whocast.pick_size(args.size),
        mode=whocast.pick_mode(args.mode),
        width=args.width,
        db=db,
    )


def run_signature_command(session):
    """RunSignatureCommand Prints the character's Signature phrase,
       or Reports it has none."""
    if not session.signature:
        print("whonews: '{}' has no signature phrase".format(session.display_name), file=sys.stderr)
        return 1
    print_title(session.mode, session.signature_label.format(session.display_name))
    print_character_panel(session, session.signature)
    return 0


def run_anecdote_command(session, requested):
    """RunAnecdoteCommand Tells a brief Anecdote with the requested or a random other Character."""
    cast = resolve_anecdote_cast(requested, session.character)
    if not cast:
        print("whonews: no character to tell an anecdote with", file=sys.stderr)
        return 1
    print_title(session.mode, session.anecdote_label.format(session.display_name))
    take = render_take_safely(
        render_character_anecdote, session.backend,
        session.persona, cast, session.backend, session.display_name)
    if take is None:
        return print_canned_line(session)
    print_character_panel(session, take or session.fallback)
    return 0


def replay_archived_take(session):
    """ReplayArchivedTake Prints the character's newest archived Take when the model stayed silent,
       or its canned Line when the archive is empty."""
    rows = load_take_history(session.db, 1, session.character)
    if not rows:
        return print_canned_line(session)
    headline, source, take, when = rows[0]
    print("whonews: no take today; replaying the archive", file=sys.stderr)
    print_dated_title(session.mode, time.strftime("%Y-%m-%d %H:%M", time.localtime(when)),
                      format_headline(headline, source))
    print_character_panel(session, take)
    return 0


def print_canned_line(session):
    """PrintCannedLine Prints the character's fallback quip — its signature phrase when it has no other —
       the last thing left to say when nothing answered."""
    print_character_panel(session, session.fallback)
    return 0


def run_history_command(session, count):
    """RunHistoryCommand Replays the last `count` archived Takes for this Character."""
    rows = load_take_history(session.db, count, session.character)
    if not rows:
        print("whonews: nothing archived yet", file=sys.stderr)
        return 1
    for headline, source, take, when in rows:
        stamp = time.strftime("%Y-%m-%d %H:%M", time.localtime(when))
        print_dated_title(session.mode, stamp, format_headline(headline, source))
        print_character_panel(session, take)
        print()
    return 0


def run_news_command(session, args):
    """RunNewsCommand Picks a Headline,
       then Prints a joke/anecdote/signature/opinion about the day's News.

    With no headlines to comment on — offline, or an empty feed — it replays
    the archive instead of printing nothing.
    """
    stories = fetch_daily_stories(session, args)
    if not stories:
        print_title(session.mode, session.news_label.format(session.display_name))
        return replay_archived_take(session)

    if args.headlines:
        return print_random_headline(session, stories)

    others = [c for c in whocast.list_characters() if c != session.character]
    if session.signature and random.random() < args.signature_chance:
        return run_signature_command(session)
    if others and random.random() < args.anecdote_chance:
        return run_anecdote_command(session, None)
    if random.random() < args.joke_chance:
        return run_joke_command(session)

    return run_opine_command(session, args, stories)


def fetch_daily_stories(session, args):
    """FetchDailyStories Returns today's Headlines,
       or None after reporting why they're unavailable.

    Empty and None both mean "no news today"; the caller falls back to the
    archive either way.
    """
    url = build_news_url(args.topic, session.query, session.region, session.lang)
    ttl = 0 if args.refresh else args.ttl * 60
    try:
        return parse_headlines(fetch_feed_body(url, session.db, ttl), args.count)
    except (urllib.error.URLError, ET.ParseError, OSError) as e:
        print("whonews: could not read Google News: {}".format(e), file=sys.stderr)
        return None


def print_random_headline(session, stories):
    """PrintRandomHeadline Prints one random Headline from stories, with its Source and today's date."""
    print_title(session.mode, session.news_label.format(session.display_name))
    headline, source = random.choice(stories)
    print_dated_title(session.mode, time.strftime("%Y-%m-%d"), format_headline(headline, source))
    return 0


def run_joke_command(session):
    """RunJokeCommand Tells a standalone character Joke instead of commenting on the News."""
    print_title(session.mode, session.joke_label.format(session.display_name))
    take = render_take_safely(
        render_character_joke, session.backend,
        session.persona, session.joke_prompt, session.backend, session.display_name)
    if take is None:
        return print_canned_line(session)
    print_character_panel(session, take or session.fallback)
    return 0


def run_opine_command(session, args, stories):
    """RunOpineCommand Picks a Headline,
       reuses a cached Take or asks the model,
       then Prints it."""
    headline, source = random.choice(stories)
    print_title(session.mode, session.news_label.format(session.display_name))

    take = None if args.refresh else load_cached_take(
        session.db, headline, session.backend.model, session.character)
    if take is None:
        take = render_take_safely(
            render_headline_take, session.backend,
            session.persona, headline, session.backend, session.display_name)
        if take is None:
            return replay_archived_take(session)
        if take:
            store_take(session.db, headline, session.backend.model, session.character, source, take)

    print_dated_title(session.mode, time.strftime("%Y-%m-%d"), format_headline(headline, source))
    print_character_panel(session, take or session.fallback)
    return 0


# ------------------------------------------------------------------ character


def resolve_anecdote_cast(requested, character):
    """ResolveAnecdoteCast Returns the display name of the requested or a random other Character."""
    if requested:
        try:
            return whocast.load_character(requested).get("display_name", requested)
        except whocast.CharacterNotFound:
            print("whonews: unknown character '{}'".format(requested), file=sys.stderr)
            return None
    others = [c for c in whocast.list_characters() if c != character]
    if not others:
        return None
    other = random.choice(others)
    try:
        return whocast.load_character(other).get("display_name", other)
    except whocast.CharacterNotFound:
        return other


# ------------------------------------------------------------------ cache
#
# Inline rather than a schema.sql file: one less loose file to find (and
# bundle) when whonews.py is symlinked or frozen into a standalone binary.
#
# feeds — the raw RSS body per URL, reused for --ttl minutes and pruned
#         after a day (FEED_KEEP below). Shared by every character, since
#         headlines don't depend on who's commenting on them.
# takes — one opinion per (headline, model, character), kept for
#         --prune days (TAKE_KEEP_DAYS below). Replaying a stored take
#         costs milliseconds instead of a model call.
SCHEMA = """
CREATE TABLE IF NOT EXISTS feeds (
    url        TEXT PRIMARY KEY,
    fetched_at REAL NOT NULL,
    body       BLOB NOT NULL
);
CREATE TABLE IF NOT EXISTS takes (
    headline   TEXT NOT NULL,
    model      TEXT NOT NULL,
    character  TEXT NOT NULL,
    source     TEXT,
    take       TEXT NOT NULL,
    created_at REAL NOT NULL,
    PRIMARY KEY (headline, model, character)
);
CREATE INDEX IF NOT EXISTS takes_by_date ON takes (created_at DESC);
"""


def resolve_db_path():
    """ResolveDbPath Returns the cache database Path, from $WHONEWS_DB or the Xdg cache Default."""
    env = os.environ.get("WHONEWS_DB")
    if env:
        return env
    base = os.environ.get("XDG_CACHE_HOME") or os.path.join(
        os.path.expanduser("~"), ".cache")
    return os.path.join(base, "whosay", "news.db")


def open_news_cache(path, prune_days=TAKE_KEEP_DAYS):
    """OpenNewsCache Connects to the Sqlite file at path,
       preps its Schema,
       then Returns it (None on disk trouble)."""
    try:
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        db = sqlite3.connect(path, timeout=5)
        db.executescript(SCHEMA)
        clear_stale_feeds(db)
        dropped = prune_old_takes(db, prune_days)
        db.commit()
        report_pruned_takes(dropped, prune_days)
        return db
    except (sqlite3.Error, OSError) as e:
        print("whonews: cache disabled ({})".format(e), file=sys.stderr)
        return None


def clear_stale_feeds(db):
    """ClearStaleFeeds Deletes cached feed Rows older than FEED_KEEP."""
    db.execute("DELETE FROM feeds WHERE fetched_at < ?", (time.time() - FEED_KEEP,))


def prune_old_takes(db, days):
    """PruneOldTakes Deletes archived Takes older than `days`,
       then Returns how many were dropped."""
    if db is None or days <= 0:
        return 0
    cur = db.execute("DELETE FROM takes WHERE created_at < ?",
                     (time.time() - days * 86400,))
    return cur.rowcount


def report_pruned_takes(dropped, prune_days):
    """ReportPrunedTakes Prints how many archived Takes were dropped, when any were."""
    if dropped:
        print("whonews: pruned {} take{} older than {:g} days".format(
            dropped, "" if dropped == 1 else "s", prune_days), file=sys.stderr)


def load_cached_feed(db, url, ttl):
    """LoadCachedFeed Returns the cached feed Body for url if still within ttl,
       else None."""
    if db is None or ttl <= 0:
        return None
    row = db.execute(
        "SELECT body FROM feeds WHERE url = ? AND fetched_at > ?",
        (url, time.time() - ttl),
    ).fetchone()
    return row[0] if row else None


def store_feed(db, url, body):
    """StoreFeed Saves the feed Body for url, stamped with the current Time."""
    if db is None:
        return
    db.execute("INSERT OR REPLACE INTO feeds (url, fetched_at, body) VALUES (?, ?, ?)",
               (url, time.time(), body))
    db.commit()


def load_cached_take(db, headline, model, character):
    """LoadCachedTake Returns a previously stored Take for this headline/model/character,
       or None."""
    if db is None:
        return None
    row = db.execute(
        "SELECT take FROM takes WHERE headline = ? AND model = ? AND character = ?",
        (headline, model, character)).fetchone()
    return row[0] if row else None


def store_take(db, headline, model, character, source, take):
    """StoreTake Saves one character's Take on a headline, stamped with the current Time."""
    if db is None:
        return
    db.execute(
        "INSERT OR REPLACE INTO takes (headline, model, character, source, take, created_at) "
        "VALUES (?, ?, ?, ?, ?, ?)",
        (headline, model, character, source, take, time.time()),
    )
    db.commit()


def load_take_history(db, limit, character):
    """LoadTakeHistory Returns this character's last `limit` archived Takes, newest first."""
    if db is None:
        return []
    return db.execute(
        "SELECT headline, source, take, created_at FROM takes "
        "WHERE character = ? ORDER BY created_at DESC LIMIT ?",
        (character, limit)).fetchall()


# ------------------------------------------------------------------ news


def build_news_url(topic=None, query=None, region=DEFAULT_REGION, lang=DEFAULT_LANG):
    """BuildNewsUrl Returns the Google News Rss url for a search Query, a topic Section, or the front page."""
    tail = urllib.parse.urlencode({"hl": lang, "gl": region,
                                   "ceid": "{}:{}".format(region, lang.split("-")[0])})
    if query:
        q = urllib.parse.quote(query)
        return "{}/search?q={}&{}".format(GOOGLE_NEWS_BASE_URL, q, tail)
    if topic:
        return "{}/headlines/section/topic/{}?{}".format(
            GOOGLE_NEWS_BASE_URL, topic.upper(), tail)
    return "{}?{}".format(GOOGLE_NEWS_BASE_URL, tail)


def fetch_feed_body(url, db, ttl):
    """FetchFeedBody Returns the feed's raw Xml, from cache when fresh,
       else over the network.

    If the network fetch fails, falls back to a stale cached copy (up to
    FEED_KEEP old) rather than giving up outright.
    """
    body = load_cached_feed(db, url, ttl)
    if body is not None:
        return body
    req = urllib.request.Request(url, headers={"User-Agent": "whonews/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            body = r.read()
    except (urllib.error.URLError, OSError):
        stale = load_stale_feed(db, url)
        if stale is not None:
            return stale
        raise
    store_feed(db, url, body)
    return body


def load_stale_feed(db, url):
    """LoadStaleFeed Returns any cached Body for url, however old — last resort when offline."""
    if db is None:
        return None
    row = db.execute("SELECT body FROM feeds WHERE url = ?", (url,)).fetchone()
    return row[0] if row else None


def parse_headlines(raw, count):
    """ParseHeadlines Returns [(headline, source), ...] parsed from a Google News Rss body."""
    root = ET.fromstring(raw)
    out, seen = [], set()
    for item in root.iter("item"):
        title = (item.findtext("title") or "").strip()
        if not title:
            continue
        title = html.unescape(title)
        src = item.find("source")
        source = (src.text or "").strip() if src is not None else ""
        # Google appends " - Outlet" to the title; drop it, we show it apart.
        if source and title.endswith(" - " + source):
            title = title[: -len(source) - 3].strip()
        title = re.sub(r"\s+", " ", title)
        key = title.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append((title, source))
        if len(out) >= count:
            break
    return out


def format_headline(headline, source):
    """FormatHeadline Appends the Source in parens to the Headline, when there is one."""
    return "{}{}".format(headline, " ({})".format(source) if source else "")


# ------------------------------------------------------------------ model
#
# Each provider is a call(persona, prompt, backend) -> raw text function.
# Add a new one here (plus its port in PROVIDER_PORTS and its default model
# in DEFAULT_MODELS) to support another backend.


@dataclass(frozen=True)
class ModelBackend:
    """ModelBackend Bundles which Api answers a Take, with the Credential and Endpoint it needs."""
    provider: str
    model: str
    timeout: float
    api_key: str
    base_url: str


def ask_character(persona, prompt, backend, display_name):
    """AskCharacter Calls the configured Provider,
       then Returns its reply cleaned to one Line."""
    answer = PROVIDERS[backend.provider](persona, prompt, backend)
    return clean_model_reply(answer, display_name)


def render_headline_take(persona, headline, backend, display_name):
    """RenderHeadlineTake Asks the character for a one-line Opinion about the Headline."""
    return ask_character(persona, "Titular: {}".format(headline), backend, display_name)


def render_character_joke(persona, joke_prompt, backend, display_name):
    """RenderCharacterJoke Asks the character for a standalone Joke instead of a news Take."""
    return ask_character(persona, joke_prompt, backend, display_name)


def render_character_anecdote(persona, other, backend, display_name):
    """RenderCharacterAnecdote Asks the character for a brief Anecdote alongside the given other Character."""
    prompt = (
        "Inventa una anécdota breve, en tu propio estilo, en la que tú y {}\n"
        "sean los protagonistas.\n"
        "Make up a brief anecdote, in your own style, in which you and {}\n"
        "are the protagonists."
    ).format(other, other)
    return ask_character(persona, prompt, backend, display_name)


def render_take_safely(render, backend, *args):
    """RenderTakeSafely Calls a take-Renderer,
       turning any model Failure into a printed whonews Message.

    Returns None when the call failed (having already explained why to stderr);
    callers that get None back should exit 1.
    """
    try:
        return render(*args)
    except RuntimeError as e:
        print("whonews: {}".format(e), file=sys.stderr)
    except urllib.error.URLError as e:
        print(format_model_error(backend, e), file=sys.stderr)
    except OSError as e:
        print("whonews: model error: {}".format(e), file=sys.stderr)
    return None


def format_model_error(backend, e):
    """FormatModelError Returns a friendly whonews Message for a network/model-call Failure."""
    reason = read_api_reason(e) or e
    if backend.provider == "ollama":
        return ("whonews: no answer from the local model at {} ({}). "
                 "Is `llama-server` running?".format(backend.base_url, reason))
    return "whonews: no answer from {} at {} ({})".format(
        backend.provider, backend.base_url, reason)


def read_api_reason(e):
    """ReadApiReason Returns the Message an http Error carries in its Json body,
       so a 400 says why instead of just "Bad Request".

    Returns None when the failure carries no readable Json message,
    which leaves the caller with the bare urllib Error.
    """
    if not isinstance(e, urllib.error.HTTPError):
        return None
    try:
        body = json.loads(e.read())
    except (ValueError, OSError):
        return None
    message = body.get("error", {}).get("message") if isinstance(body, dict) else None
    return "HTTP {}: {}".format(e.code, message) if message else None


GENERIC_LABEL = r"opini[oó]n|respuesta"


def clean_model_reply(text, display_name):
    """CleanModelReply Strips think-tags, name/label prefixes and padding,
       then Returns the first real Line."""
    # Models sometimes echo the character's name, or a generic label, before
    # the actual line ("Carmen Gloria: ...", "Opinión: ...") — strip it.
    label = r"{}|{}".format(re.escape(display_name), GENERIC_LABEL)
    line_re = re.compile(r"^\W*(?:{})\s*:?\W*$".format(label), re.I)
    prefix_re = re.compile(r"^(?:{})\s*:\s*".format(label), re.I)

    text = re.sub(r"<think>.*?</think>", "", text, flags=re.S | re.I)
    lines = [l.strip(" *_#").strip() for l in text.split("\n")]
    lines = [l for l in lines if l and not line_re.match(l)]
    text = lines[0] if lines else ""
    text = prefix_re.sub("", text)
    return text.strip().strip('"“”').strip()


def build_model_backend(args):
    """BuildModelBackend Resolves the model, Credential and Endpoint for the chosen Provider,
       then Returns the Backend that answers every Take."""
    provider = args.provider
    return ModelBackend(
        provider=provider,
        model=args.model or os.environ.get("WHONEWS_MODEL") or DEFAULT_MODELS[provider],
        timeout=args.timeout,
        api_key=resolve_api_key(provider, args),
        base_url=resolve_base_url(provider, args),
    )


def resolve_default_provider(args):
    """ResolveDefaultProvider Returns the backend to use when --provider was not given:
       $WHONEWS_PROVIDER,
       else the local llama-server.

    A key lying around no longer picks its provider: the local server is free,
    so paying for a call is something you ask for, never something you drift into.
    """
    return os.environ.get("WHONEWS_PROVIDER") or DEFAULT_PROVIDER


def resolve_api_key(provider, args):
    """ResolveApiKey Returns the provider's Credential, from the command line or the Environment,
       or None when it has none (or needs none)."""
    port = PROVIDER_PORTS[provider]
    if not port.key_arg:
        return None
    return getattr(args, port.key_arg, None) or os.environ.get(port.key_env) or None


def resolve_base_url(provider, args):
    """ResolveBaseUrl Returns the provider's Endpoint, from the command line, the Environment
       or its own Default, with the Scheme filled in and the trailing Slash dropped."""
    port = PROVIDER_PORTS[provider]
    url = (getattr(args, port.url_arg, None) or os.environ.get(port.url_env)
           or port.default_url)
    if not url.startswith("http"):
        url = "http://" + url
    return url.rstrip("/")


def _post_json(url, body, timeout, headers=None):
    """PostJson Sends body as Json to url,
       then Returns the decoded Json response."""
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(),
        headers=dict(headers or {}, **{"Content-Type": "application/json"}),
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def _call_ollama(persona, prompt, backend):
    """CallOllama Asks a local llama.cpp server for a raw Reply, via its OpenAI-compatible Api.

    The provider key stays "ollama" for backward compatibility with existing
    --provider/$WHONEWS_PROVIDER usage, even though it now talks to a local
    llama-server instance instead of the Ollama daemon.
    """
    body = {
        "model": backend.model,
        "messages": [
            {"role": "system", "content": persona},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.9,
        "top_p": 0.95,
        "max_tokens": 200,
    }
    data = _post_json(backend.base_url + "/v1/chat/completions", body, backend.timeout)
    return data["choices"][0]["message"]["content"]


def _call_anthropic(persona, prompt, backend):
    """CallAnthropic Asks the Anthropic Api for a raw Reply."""
    if not backend.api_key:
        raise RuntimeError("no anthropic key: pass --anthropic-key or set ANTHROPIC_API_KEY")
    body = {
        "model": backend.model,
        "system": persona,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 200,
        "temperature": 0.9,
    }
    data = _post_json(
        backend.base_url + "/v1/messages", body, backend.timeout,
        headers={"x-api-key": backend.api_key, "anthropic-version": "2023-06-01"},
    )
    return "".join(p.get("text", "") for p in data.get("content", []))


def _call_openai(persona, prompt, backend):
    """CallOpenai Asks the OpenAI Api for a raw Reply."""
    if not backend.api_key:
        raise RuntimeError("no openai key: pass --openai-key or set OPENAI_API_KEY")
    body = {
        "model": backend.model,
        "messages": [
            {"role": "system", "content": persona},
            {"role": "user", "content": prompt},
        ],
        "max_tokens": 200,
        "temperature": 0.9,
    }
    data = _post_json(
        backend.base_url + "/v1/chat/completions", body, backend.timeout,
        headers={"Authorization": "Bearer " + backend.api_key},
    )
    return data["choices"][0]["message"]["content"]


PROVIDERS = {
    "ollama": _call_ollama,
    "anthropic": _call_anthropic,
    "openai": _call_openai,
}


# ------------------------------------------------------------------ output


def print_title(mode, text):
    """PrintTitle Prints a bold Title,
       or plain text when mode is mono."""
    print("\033[1m{}\033[0m".format(text) if mode != "mono" else text)


def print_dated_title(mode, stamp, text):
    """PrintDatedTitle Prints a colored date Stamp beside a bold Title,
       or plain text when mode is mono."""
    if mode != "mono":
        print("\033[36m{}\033[0m  \033[1m{}\033[0m".format(stamp, text))
    else:
        print("{}  {}".format(stamp, text))


def print_character_panel(session, text):
    """PrintCharacterPanel Prints one Panel in this session's look: the Bubble above the Portrait."""
    whocast.print_character_panel(
        text,
        whocast.load_character_art(session.character, session.size, session.mode),
        session.size, session.width)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (BrokenPipeError, KeyboardInterrupt):
        pass
