#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
whonews — the day's headlines, read out loud by a character.

Pulls the top stories from Google News RSS and, 70% of the time (by default),
asks an AI backend for a short opinion in the character's voice about one of
them picked at random; 10% of the time the character skips the news and just
cracks a sarcastic joke; 10% it invents a brief anecdote with one other
random character; and the remaining 10%, it just drops its signature phrase.
Either way, prints one panel through whosay. --joke-chance, --anecdote-chance
and --signature-chance change the split.

Ollama (local, free) is the default backend; --provider switches to
Anthropic or OpenAI, reading ANTHROPIC_API_KEY / OPENAI_API_KEY from the
environment.

This is a parody: the opinions are generated by a language model, not real
quotes from anyone.

Usage:
    whonews.py                          # one random take, Chile, small portrait
    whonews.py -n 10 -b                 # pick from a bigger pool, big portrait
    whonews.py -C some_character        # a different character's take
    whonews.py --random                 # a random character's take
    whonews.py --topic WORLD            # a Google News section
    whonews.py --query "inteligencia artificial"
    whonews.py --headlines              # no model, just one random headline
    whonews.py --model gemma4:latest    # sharper takes, far slower
    whonews.py --refresh                # ignore the cache, ask again

Feeds and opinions are cached in SQLite (~/.cache/whosay/news.db), so a
second run costs nothing and the takes pile up into an archive. A fetched
feed is reused for --ttl minutes (default a day) before being re-fetched,
and cached feed bodies are kept for a day regardless so a fetch that fails
(e.g. offline) can fall back to the last cached copy; if there's no cached
copy at all, the character's signature phrase is printed instead. Takes
older than a week are dropped on the next run; --prune changes that.

Options:
    -n N              pool size to pick a headline from at random (default 5)
    -C, --character   which character comments (default carmen_gloria)
    --random          a random character comments
    --topic NAME      WORLD, NATION, BUSINESS, TECHNOLOGY, SCIENCE, SPORTS,
                      ENTERTAINMENT, HEALTH
    --query TEXT      search instead of browsing a section
                      (default: the character's "topic" field)
    --region CODE     country code for Google News
                      (default: from the character's "nationality", else CL)
    --lang CODE       language code
                      (default: from the character's "language", else es-419)
    --provider NAME   ollama, anthropic or openai
                      (default $WHONEWS_PROVIDER or ollama)
    --model NAME      model for the chosen provider
                      (default $WHONEWS_MODEL, else the provider's own
                      default: llama3.2:1b / claude-haiku-4-5-20251001 /
                      gpt-4o-mini)
    --headlines       skip the model, print the raw headlines
    --timeout SEC     per-request timeout for the model (default 120)
    --db PATH         cache location ($WHONEWS_DB overrides the default)
    --ttl MIN         how long a cached feed stays fresh (default 1440 = 1 day)
    --refresh         re-fetch the feed and re-ask the model
    --no-cache        don't read or write the cache at all
    --history [N]     print the last N archived takes and exit
    --prune DAYS      drop takes older than DAYS (default 7, 0 keeps all)
    --joke-chance P   chance (0-1) of a standalone joke instead of a news
                      take (default 0.1)
    --anecdote-chance P
                      chance (0-1) the character tells a brief anecdote with
                      another character instead (default 0.1)
    --signature-chance P
                      chance (0-1) the character just drops its signature
                      phrase instead (default 0.1)
    --signature       always print the signature phrase and exit
    --anecdote [NAME]
                      always tell a brief anecdote and exit; optionally give
                      which character stars in it (default: one random)
    plus every whosay look flag: -s/-m/-b, -c/-a/-W
"""
import argparse
import html
import json
import os
import random
import re
import sqlite3
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from dataclasses import dataclass

# Works when whonews is reached through a symlink in ~/.local/bin too.
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
import whosay  # noqa: E402

__version__ = "1.0"

# ------------------------------------------------------------------ defaults
GOOGLE_NEWS_BASE_URL = "https://news.google.com/rss"
DEFAULT_CHARACTER = "carmen_gloria"
DEFAULT_COUNT = 5        # headline pool size to pick from
DEFAULT_REGION = "CL"    # Google News region, when the character has none
DEFAULT_LANG = "es-419"  # Google News language, when the character has none
DEFAULT_PROVIDER = "ollama"
DEFAULT_TIMEOUT = 120    # seconds, per model request
DEFAULT_WIDTH = 40
DEFAULT_HISTORY_N = 10   # --history with no count given
DEFAULT_TTL_MIN = 1440   # feed cache freshness, in minutes (1 day)
FEED_KEEP = 24 * 3600    # cached feed bodies are worthless after a day
TAKE_KEEP_DAYS = 7       # the archive is small, but not immortal
JOKE_CHANCE = 0.1        # how often the character skips the news for a joke instead
ANECDOTE_CHANCE = 0.1    # how often the character tells an anecdote with another instead
SIGNATURE_CHANCE = 0.1   # how often the character just drops its signature phrase
DEFAULT_MODELS = {
    "ollama": "llama3.2:1b",
    "anthropic": "claude-haiku-4-5-20251001",
    "openai": "gpt-4o-mini",
}
INDENT = {"small": 1, "medium": 2, "big": 4}

SECTIONS = ("WORLD", "NATION", "BUSINESS", "TECHNOLOGY", "SCIENCE", "SPORTS",
            "ENTERTAINMENT", "HEALTH")

# Maps a character.json "nationality"/"language" value to the Google News
# region/lang code it implies. Add an entry here when a new character's
# nationality or language isn't one of these yet.
NATIONALITY_REGION = {
    "Chilean": "CL",
    "Argentine": "AR",
    "Mexican": "MX",
    "Peruvian": "PE",
    "Colombian": "CO",
    "Spanish": "ES",
    "American": "US",
    "British": "GB",
}
LANGUAGE_CODE = {
    "Spanish": "es-419",
    "English": "en-US",
    "Portuguese": "pt-BR",
}

# Header line printed before the headline/joke/anecdote/signature, in the
# character's language. (news_label, joke_label, anecdote_label, signature_label),
# each formatted with the character's display name.
LABELS = {
    "Spanish": ("Noticias con {}", "Chiste con {}", "Anécdota con {}", "La frase de {}"),
    "English": ("News with {}", "Joke with {}", "Anecdote with {}", "The catchphrase of {}"),
    "Portuguese": ("Notícias com {}", "Piada com {}", "Anedota com {}", "A frase de {}"),
}


# ------------------------------------------------------------------ character


def load_character(name):
    """LoadCharacter Reads characters/<name>/character.json, then Returns it as a dict."""
    path = os.path.join(os.path.dirname(os.path.realpath(__file__)),
                         "characters", name, "character.json")
    try:
        with open(path, encoding="utf-8") as f:
            return json.load(f)
    except OSError:
        available = ", ".join(whosay.list_characters()) or "none found"
        raise whosay.CharacterNotFound(
            "unknown character '{}' (available: {})".format(name, available))


# ------------------------------------------------------------------ cache
#
# Inline rather than a schema.sql file: one less loose file to find (and
# bundle) when whonews.py is symlinked or frozen into a standalone binary.
#
# feeds — the raw RSS body per URL, reused for --ttl minutes and pruned
#         after a day (FEED_KEEP below). Shared by every character, since
#         headlines don't depend on who's commenting on them.
# takes — one opinion per (headline, model, character), kept for
#         --prune days (TAKE_KEEP_DAYS below). Replaying a stored take
#         costs milliseconds instead of a model call.
SCHEMA = """
CREATE TABLE IF NOT EXISTS feeds (
    url        TEXT PRIMARY KEY,
    fetched_at REAL NOT NULL,
    body       BLOB NOT NULL
);
CREATE TABLE IF NOT EXISTS takes (
    headline   TEXT NOT NULL,
    model      TEXT NOT NULL,
    character  TEXT NOT NULL,
    source     TEXT,
    take       TEXT NOT NULL,
    created_at REAL NOT NULL,
    PRIMARY KEY (headline, model, character)
);
CREATE INDEX IF NOT EXISTS takes_by_date ON takes (created_at DESC);
"""


def resolve_db_path():
    """ResolveDbPath Returns the cache database Path, from $WHONEWS_DB or the Xdg cache Default."""
    env = os.environ.get("WHONEWS_DB")
    if env:
        return env
    base = os.environ.get("XDG_CACHE_HOME") or os.path.join(
        os.path.expanduser("~"), ".cache")
    return os.path.join(base, "whosay", "news.db")


def clear_stale_feeds(db):
    """ClearStaleFeeds Deletes cached feed Rows older than FEED_KEEP."""
    db.execute("DELETE FROM feeds WHERE fetched_at < ?", (time.time() - FEED_KEEP,))


def prune_old_takes(db, days):
    """PruneOldTakes Deletes archived Takes older than `days`, then Returns how many were dropped."""
    if db is None or days <= 0:
        return 0
    cur = db.execute("DELETE FROM takes WHERE created_at < ?",
                     (time.time() - days * 86400,))
    return cur.rowcount


def report_pruned_takes(dropped, prune_days):
    """ReportPrunedTakes Prints how many archived Takes were dropped, when any were."""
    if dropped:
        print("whonews: pruned {} take{} older than {:g} days".format(
            dropped, "" if dropped == 1 else "s", prune_days), file=sys.stderr)


def open_news_cache(path, prune_days=TAKE_KEEP_DAYS):
    """OpenNewsCache Connects to the Sqlite file at path, preps its Schema, then Returns it (None on disk trouble)."""
    try:
        parent = os.path.dirname(path)
        if parent:
            os.makedirs(parent, exist_ok=True)
        db = sqlite3.connect(path, timeout=5)
        db.executescript(SCHEMA)
        clear_stale_feeds(db)
        dropped = prune_old_takes(db, prune_days)
        db.commit()
        report_pruned_takes(dropped, prune_days)
        return db
    except (sqlite3.Error, OSError) as e:
        print("whonews: cache disabled ({})".format(e), file=sys.stderr)
        return None


def load_cached_feed(db, url, ttl):
    """LoadCachedFeed Returns the cached feed Body for url if still within ttl, else None."""
    if db is None or ttl <= 0:
        return None
    row = db.execute(
        "SELECT body FROM feeds WHERE url = ? AND fetched_at > ?",
        (url, time.time() - ttl),
    ).fetchone()
    return row[0] if row else None


def store_feed(db, url, body):
    """StoreFeed Saves the feed Body for url, stamped with the current Time."""
    if db is None:
        return
    db.execute("INSERT OR REPLACE INTO feeds (url, fetched_at, body) VALUES (?, ?, ?)",
               (url, time.time(), body))
    db.commit()


def load_cached_take(db, headline, model, character):
    """LoadCachedTake Returns a previously stored Take for this headline/model/character, or None."""
    if db is None:
        return None
    row = db.execute(
        "SELECT take FROM takes WHERE headline = ? AND model = ? AND character = ?",
        (headline, model, character)).fetchone()
    return row[0] if row else None


def store_take(db, headline, model, character, source, take):
    """StoreTake Saves one character's Take on a headline, stamped with the current Time."""
    if db is None:
        return
    db.execute(
        "INSERT OR REPLACE INTO takes (headline, model, character, source, take, created_at) "
        "VALUES (?, ?, ?, ?, ?, ?)",
        (headline, model, character, source, take, time.time()),
    )
    db.commit()


def load_take_history(db, limit, character):
    """LoadTakeHistory Returns this character's last `limit` archived Takes, newest first."""
    if db is None:
        return []
    return db.execute(
        "SELECT headline, source, take, created_at FROM takes "
        "WHERE character = ? ORDER BY created_at DESC LIMIT ?",
        (character, limit)).fetchall()


# ------------------------------------------------------------------ news


def build_news_url(topic=None, query=None, region=DEFAULT_REGION, lang=DEFAULT_LANG):
    """BuildNewsUrl Returns the Google News Rss url for a search Query, a topic Section, or the front page."""
    tail = urllib.parse.urlencode({"hl": lang, "gl": region,
                                   "ceid": "{}:{}".format(region, lang.split("-")[0])})
    if query:
        q = urllib.parse.quote(query)
        return "{}/search?q={}&{}".format(GOOGLE_NEWS_BASE_URL, q, tail)
    if topic:
        return "{}/headlines/section/topic/{}?{}".format(
            GOOGLE_NEWS_BASE_URL, topic.upper(), tail)
    return "{}?{}".format(GOOGLE_NEWS_BASE_URL, tail)


def load_stale_feed(db, url):
    """LoadStaleFeed Returns any cached Body for url, however old — last resort when offline."""
    if db is None:
        return None
    row = db.execute("SELECT body FROM feeds WHERE url = ?", (url,)).fetchone()
    return row[0] if row else None


def fetch_feed_body(url, db, ttl):
    """FetchFeedBody Returns the feed's raw Xml, from cache when fresh, else over the network.

    If the network fetch fails, falls back to a stale cached copy (up to
    FEED_KEEP old) rather than giving up outright.
    """
    body = load_cached_feed(db, url, ttl)
    if body is not None:
        return body
    req = urllib.request.Request(url, headers={"User-Agent": "whonews/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            body = r.read()
    except (urllib.error.URLError, OSError):
        stale = load_stale_feed(db, url)
        if stale is not None:
            return stale
        raise
    store_feed(db, url, body)
    return body


def parse_headlines(raw, count):
    """ParseHeadlines Returns [(headline, source), ...] parsed from a Google News Rss body."""
    root = ET.fromstring(raw)
    out, seen = [], set()
    for item in root.iter("item"):
        title = (item.findtext("title") or "").strip()
        if not title:
            continue
        title = html.unescape(title)
        src = item.find("source")
        source = (src.text or "").strip() if src is not None else ""
        # Google appends " - Outlet" to the title; drop it, we show it apart.
        if source and title.endswith(" - " + source):
            title = title[: -len(source) - 3].strip()
        title = re.sub(r"\s+", " ", title)
        key = title.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append((title, source))
        if len(out) >= count:
            break
    return out


def format_headline(headline, source):
    """FormatHeadline Appends the Source in parens to the Headline, when there is one."""
    return "{}{}".format(headline, " ({})".format(source) if source else "")


# ------------------------------------------------------------------ model
#
# Each provider is a call(persona, prompt, model, timeout) -> raw text
# function. Add a new one here (plus its default model in DEFAULT_MODELS)
# to support another backend.


def resolve_ollama_host():
    """ResolveOllamaHost Returns the Ollama server Url, from $OLLAMA_HOST or the local Default."""
    host = os.environ.get("OLLAMA_HOST", "127.0.0.1:11434")
    if not host.startswith("http"):
        host = "http://" + host
    return host.rstrip("/")


def _post_json(url, body, timeout, headers=None):
    """PostJson Sends body as Json to url, then Returns the decoded Json response."""
    req = urllib.request.Request(
        url, data=json.dumps(body).encode(),
        headers=dict(headers or {}, **{"Content-Type": "application/json"}),
    )
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.loads(r.read())


def _call_ollama(persona, prompt, model, timeout):
    """CallOllama Asks a local Ollama model for a raw Reply, retrying once without `think` if refused."""
    body = {
        "model": model,
        "system": persona,
        "prompt": prompt,
        "stream": False,
        # Reasoning models burn the whole budget thinking and answer nothing.
        "think": False,
        "options": {"temperature": 0.9, "top_p": 0.95, "num_predict": 200},
    }
    url = resolve_ollama_host() + "/api/generate"
    try:
        data = _post_json(url, body, timeout)
    except urllib.error.HTTPError as e:
        if e.code != 400:
            raise
        body.pop("think")  # older Ollama, or a model that rejects the flag
        body["options"]["num_predict"] = 600
        data = _post_json(url, body, timeout)
    return data.get("response", "")


def _call_anthropic(persona, prompt, model, timeout):
    """CallAnthropic Asks the Anthropic Api for a raw Reply."""
    key = os.environ.get("ANTHROPIC_API_KEY")
    if not key:
        raise RuntimeError("ANTHROPIC_API_KEY is not set")
    body = {
        "model": model,
        "system": persona,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 200,
        "temperature": 0.9,
    }
    data = _post_json(
        "https://api.anthropic.com/v1/messages", body, timeout,
        headers={"x-api-key": key, "anthropic-version": "2023-06-01"},
    )
    return "".join(p.get("text", "") for p in data.get("content", []))


def _call_openai(persona, prompt, model, timeout):
    """CallOpenai Asks the OpenAI Api for a raw Reply."""
    key = os.environ.get("OPENAI_API_KEY")
    if not key:
        raise RuntimeError("OPENAI_API_KEY is not set")
    body = {
        "model": model,
        "messages": [
            {"role": "system", "content": persona},
            {"role": "user", "content": prompt},
        ],
        "max_tokens": 200,
        "temperature": 0.9,
    }
    data = _post_json(
        "https://api.openai.com/v1/chat/completions", body, timeout,
        headers={"Authorization": "Bearer " + key},
    )
    return data["choices"][0]["message"]["content"]


PROVIDERS = {
    "ollama": _call_ollama,
    "anthropic": _call_anthropic,
    "openai": _call_openai,
}


def format_model_error(provider, e):
    """FormatModelError Returns a friendly whonews Message for a network/model-call Failure."""
    if provider == "ollama":
        return ("whonews: no answer from Ollama at {} ({}). "
                 "Is `ollama serve` running?".format(resolve_ollama_host(), e))
    return "whonews: no answer from {} ({})".format(provider, e)


def ask_character(persona, prompt, provider, model, timeout, display_name):
    """AskCharacter Calls the configured Provider, then Returns its reply cleaned to one Line."""
    answer = PROVIDERS[provider](persona, prompt, model, timeout)
    return clean_model_reply(answer, display_name)


def render_headline_take(persona, headline, provider, model, timeout, display_name):
    """RenderHeadlineTake Asks the character for a one-line Opinion about the Headline."""
    return ask_character(persona, "Titular: {}".format(headline),
                         provider, model, timeout, display_name)


def render_character_joke(persona, joke_prompt, provider, model, timeout, display_name):
    """RenderCharacterJoke Asks the character for a standalone Joke instead of a news Take."""
    return ask_character(persona, joke_prompt, provider, model, timeout, display_name)


def render_character_anecdote(persona, other, provider, model, timeout, display_name):
    """RenderCharacterAnecdote Asks the character for a brief Anecdote alongside the given other Character."""
    prompt = (
        "Inventa una anécdota breve, en tu propio estilo, en la que tú y {}\n"
        "sean los protagonistas.\n"
        "Make up a brief anecdote, in your own style, in which you and {}\n"
        "are the protagonists."
    ).format(other, other)
    return ask_character(persona, prompt, provider, model, timeout, display_name)


def resolve_anecdote_cast(requested, character):
    """ResolveAnecdoteCast Returns the display name of the requested or a random other Character."""
    if requested:
        try:
            return load_character(requested).get("display_name", requested)
        except whosay.CharacterNotFound:
            print("whonews: unknown character '{}'".format(requested), file=sys.stderr)
            return None
    others = [c for c in whosay.list_characters() if c != character]
    if not others:
        return None
    other = random.choice(others)
    try:
        return load_character(other).get("display_name", other)
    except whosay.CharacterNotFound:
        return other


GENERIC_LABEL = r"opini[oó]n|respuesta"


def clean_model_reply(text, display_name):
    """CleanModelReply Strips think-tags, name/label prefixes and padding, then Returns the first real Line."""
    # Models sometimes echo the character's name, or a generic label, before
    # the actual line ("Carmen Gloria: ...", "Opinión: ...") — strip it.
    label = r"{}|{}".format(re.escape(display_name), GENERIC_LABEL)
    line_re = re.compile(r"^\W*(?:{})\s*:?\W*$".format(label), re.I)
    prefix_re = re.compile(r"^(?:{})\s*:\s*".format(label), re.I)

    text = re.sub(r"<think>.*?</think>", "", text, flags=re.S | re.I)
    lines = [l.strip(" *_#").strip() for l in text.split("\n")]
    lines = [l for l in lines if l and not line_re.match(l)]
    text = lines[0] if lines else ""
    text = prefix_re.sub("", text)
    return text.strip().strip('"“”').strip()


def render_take_safely(render, provider, *args):
    """RenderTakeSafely Calls a take-Renderer, turning any model Failure into a printed whonews Message.

    Returns None when the call failed (having already explained why to stderr);
    callers that get None back should exit 1.
    """
    try:
        return render(*args)
    except RuntimeError as e:
        print("whonews: {}".format(e), file=sys.stderr)
    except urllib.error.URLError as e:
        print(format_model_error(provider, e), file=sys.stderr)
    except OSError as e:
        print("whonews: model error: {}".format(e), file=sys.stderr)
    return None


# ------------------------------------------------------------------ output


def print_title(mode, text):
    """PrintTitle Prints a bold Title, or plain text when mode is mono."""
    print("\033[1m{}\033[0m".format(text) if mode != "mono" else text)


def print_dated_title(mode, stamp, text):
    """PrintDatedTitle Prints a colored date Stamp beside a bold Title, or plain text when mode is mono."""
    if mode != "mono":
        print("\033[36m{}\033[0m  \033[1m{}\033[0m".format(stamp, text))
    else:
        print("{}  {}".format(stamp, text))


def print_character_panel(text, character, size, mode, width):
    """PrintCharacterPanel Prints one whosay Panel: the speech Bubble above the character Portrait."""
    for line in whosay.render_speech_bubble(text, width):
        print(" " * INDENT[size] + line)
    print("\n".join(whosay.render_bubble_tail(False, INDENT[size])))
    print("\n".join(whosay.load_character_art(character, size, mode)))


# ------------------------------------------------------------------ session


@dataclass
class NewsSession:
    """NewsSession Bundles one resolved Character's voice, cache handle and look Settings."""
    character: str
    persona: str
    joke_prompt: str
    display_name: str
    fallback: str
    signature: str
    region: str
    lang: str
    query: str
    news_label: str
    joke_label: str
    anecdote_label: str
    signature_label: str
    model: str
    provider: str
    timeout: float
    size: str
    mode: str
    width: int
    db: object


def build_news_session(character, char, args):
    """BuildNewsSession Resolves region/lang/labels/model from the Character and Args, then Returns a Session."""
    region = (args.region or os.environ.get("WHONEWS_REGION")
              or NATIONALITY_REGION.get(char.get("nationality"), DEFAULT_REGION))
    lang = (args.lang or os.environ.get("WHONEWS_LANG")
            or LANGUAGE_CODE.get(char.get("language"), DEFAULT_LANG))
    query = args.query
    if not args.topic and not query:
        query = char.get("topic")
    news_label, joke_label, anecdote_label, signature_label = LABELS.get(
        char.get("language"), LABELS["Spanish"])
    model = args.model or os.environ.get("WHONEWS_MODEL") or DEFAULT_MODELS[args.provider]
    db = None if args.no_cache else open_news_cache(args.db, args.prune)

    return NewsSession(
        character=character,
        persona=char["persona"],
        joke_prompt=char["joke_prompt"],
        display_name=char.get("display_name", character),
        fallback=char.get("fallback", "..."),
        signature=char.get("signature"),
        region=region,
        lang=lang,
        query=query,
        news_label=news_label,
        joke_label=joke_label,
        anecdote_label=anecdote_label,
        signature_label=signature_label,
        model=model,
        provider=args.provider,
        timeout=args.timeout,
        size=whosay.pick_size(args.size),
        mode=whosay.pick_mode(args.mode),
        width=args.width,
        db=db,
    )


def resolve_requested_character(args):
    """ResolveRequestedCharacter Picks the named or a random Character, then Returns it with its config."""
    character = args.character
    if args.random:
        chars = whosay.list_characters()
        if not chars:
            raise whosay.CharacterNotFound("no characters found in characters/")
        character = random.choice(chars)
    return character, load_character(character)


# ------------------------------------------------------------------ commands


def run_signature_command(session):
    """RunSignatureCommand Prints the character's Signature phrase, or Reports it has none."""
    if not session.signature:
        print("whonews: '{}' has no signature phrase".format(session.display_name), file=sys.stderr)
        return 1
    print_title(session.mode, session.signature_label.format(session.display_name))
    print_character_panel(session.signature, session.character, session.size, session.mode, session.width)
    return 0


def run_anecdote_command(session, requested):
    """RunAnecdoteCommand Tells a brief Anecdote with the requested or a random other Character."""
    cast = resolve_anecdote_cast(requested, session.character)
    if not cast:
        print("whonews: no character to tell an anecdote with", file=sys.stderr)
        return 1
    print_title(session.mode, session.anecdote_label.format(session.display_name))
    take = render_take_safely(
        render_character_anecdote, session.provider,
        session.persona, cast, session.provider, session.model, session.timeout, session.display_name)
    if take is None:
        return 1
    print_character_panel(take or session.fallback, session.character, session.size, session.mode, session.width)
    return 0


def run_history_command(session, count):
    """RunHistoryCommand Replays the last `count` archived Takes for this Character."""
    rows = load_take_history(session.db, count, session.character)
    if not rows:
        print("whonews: nothing archived yet", file=sys.stderr)
        return 1
    for headline, source, take, when in rows:
        stamp = time.strftime("%Y-%m-%d %H:%M", time.localtime(when))
        print_dated_title(session.mode, stamp, format_headline(headline, source))
        print_character_panel(take, session.character, session.size, session.mode, session.width)
        print()
    return 0


def print_random_headline(session, stories):
    """PrintRandomHeadline Prints one random Headline from stories, with its Source and today's date."""
    print_title(session.mode, session.news_label.format(session.display_name))
    headline, source = random.choice(stories)
    print_dated_title(session.mode, time.strftime("%Y-%m-%d"), format_headline(headline, source))
    return 0


def run_joke_command(session):
    """RunJokeCommand Tells a standalone character Joke instead of commenting on the News."""
    print_title(session.mode, session.joke_label.format(session.display_name))
    take = render_take_safely(
        render_character_joke, session.provider,
        session.persona, session.joke_prompt, session.provider, session.model, session.timeout,
        session.display_name)
    if take is None:
        return 1
    print_character_panel(take or session.fallback, session.character, session.size, session.mode, session.width)
    return 0


def fetch_daily_stories(session, args):
    """FetchDailyStories Returns today's Headlines, or None after reporting why they're unavailable."""
    url = build_news_url(args.topic, session.query, session.region, session.lang)
    ttl = 0 if args.refresh else args.ttl * 60
    try:
        return parse_headlines(fetch_feed_body(url, session.db, ttl), args.count)
    except (urllib.error.URLError, ET.ParseError, OSError) as e:
        if session.signature:
            print("whonews: offline and cache is empty; falling back to signature", file=sys.stderr)
        else:
            print("whonews: could not read Google News: {}".format(e), file=sys.stderr)
        return None


def run_opine_command(session, args, stories):
    """RunOpineCommand Picks a Headline, reuses a cached Take or asks the model, then Prints it."""
    headline, source = random.choice(stories)
    print_title(session.mode, session.news_label.format(session.display_name))
    print_dated_title(session.mode, time.strftime("%Y-%m-%d"), format_headline(headline, source))

    take = None if args.refresh else load_cached_take(session.db, headline, session.model, session.character)
    if take is None:
        take = render_take_safely(
            render_headline_take, session.provider,
            session.persona, headline, session.provider, session.model, session.timeout, session.display_name)
        if take is None:
            return 1
        if take:
            store_take(session.db, headline, session.model, session.character, source, take)

    print_character_panel(take or session.fallback, session.character, session.size, session.mode, session.width)
    return 0


def run_news_command(session, args):
    """RunNewsCommand Picks a Headline, then Prints a joke/anecdote/signature/opinion about the day's News."""
    stories = fetch_daily_stories(session, args)
    if stories is None:
        return run_signature_command(session) if session.signature else 1
    if not stories:
        print("whonews: the feed came back empty", file=sys.stderr)
        return 1

    if args.headlines:
        return print_random_headline(session, stories)

    others = [c for c in whosay.list_characters() if c != session.character]
    if session.signature and random.random() < args.signature_chance:
        return run_signature_command(session)
    if others and random.random() < args.anecdote_chance:
        return run_anecdote_command(session, None)
    if random.random() < args.joke_chance:
        return run_joke_command(session)

    return run_opine_command(session, args, stories)


# ------------------------------------------------------------------ cli


def parse_whonews_args(argv):
    """ParseWhonewsArgs Builds the Cli parser, then Returns the parsed Args."""
    parser = argparse.ArgumentParser(
        prog="whonews",
        description="The day's headlines, with a character's opinion (parody).",
        epilog="example:\n"
               "  whonews -C ozzy -n 3\n"
               "  whonews --topic technology -a -b\n"
               "  whonews --anecdote carmen_gloria\n"
               "  whonews --history 10",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("-n", "--count", type=int, default=DEFAULT_COUNT, help="how many stories")
    chars = whosay.list_characters()
    parser.add_argument("-C", "--character", default=DEFAULT_CHARACTER, choices=chars or None,
                         help="which character comments (default: {})".format(DEFAULT_CHARACTER))
    parser.add_argument("--random", action="store_true",
                         help="pick a random character")
    parser.add_argument("--topic", choices=[s.lower() for s in SECTIONS] + list(SECTIONS),
                         help="Google News section")
    parser.add_argument("--query", help="search term instead of a section "
                         "(default: the character's favorite topic)")
    parser.add_argument("--region", default=None,
                         help="country code for Google News "
                              "(default: from the character's nationality, else {})".format(DEFAULT_REGION))
    parser.add_argument("--lang", default=None,
                         help="language code (default: from the character's "
                              "language, else {})".format(DEFAULT_LANG))
    parser.add_argument("--provider", choices=list(PROVIDERS),
                         default=os.environ.get("WHONEWS_PROVIDER", DEFAULT_PROVIDER),
                         help="AI backend: ollama, anthropic or openai "
                              "(default $WHONEWS_PROVIDER or {})".format(DEFAULT_PROVIDER))
    parser.add_argument("--model", default=None,
                         help="model name (default: $WHONEWS_MODEL, else the "
                              "provider's own default)")
    parser.add_argument("--headlines", action="store_true", help="skip the model")
    parser.add_argument("--timeout", type=float, default=DEFAULT_TIMEOUT, help="model timeout (s)")
    parser.add_argument("--db", default=resolve_db_path(), help="cache location")
    parser.add_argument("--ttl", type=float, default=DEFAULT_TTL_MIN,
                         help="feed freshness (minutes, default {} = 1 day)".format(DEFAULT_TTL_MIN))
    parser.add_argument("--refresh", action="store_true", help="re-fetch and re-ask")
    parser.add_argument("--no-cache", action="store_true", help="ignore the cache entirely")
    parser.add_argument("--history", nargs="?", type=int, const=DEFAULT_HISTORY_N, metavar="N",
                         help="print the last N archived takes and exit")
    parser.add_argument("--prune", type=float, default=TAKE_KEEP_DAYS, metavar="DAYS",
                         help="drop takes older than DAYS (default {}, 0 keeps all)".format(TAKE_KEEP_DAYS))
    parser.add_argument("--joke-chance", type=float, default=JOKE_CHANCE, metavar="P",
                         help="chance (0-1) of a standalone joke instead of a news "
                              "take (default {})".format(JOKE_CHANCE))
    parser.add_argument("--anecdote-chance", type=float, default=ANECDOTE_CHANCE, metavar="P",
                         help="chance (0-1) the character tells a brief anecdote "
                              "with another character instead (default {})".format(ANECDOTE_CHANCE))
    parser.add_argument("--signature-chance", type=float, default=SIGNATURE_CHANCE, metavar="P",
                         help="chance (0-1) the character just drops its signature "
                              "phrase instead (default {})".format(SIGNATURE_CHANCE))
    parser.add_argument("--signature", action="store_true",
                         help="always print the character's signature phrase and exit")
    parser.add_argument("--anecdote", nargs="?", const="", default=None, metavar="NAME",
                         choices=chars or None,
                         help="always tell a brief anecdote and exit; optionally give "
                              "which character stars in it (default: one random)")
    size_group = parser.add_mutually_exclusive_group()
    size_group.add_argument("-s", "--small", action="store_const", const="small", dest="size",
                             help="20-column portrait (default)")
    size_group.add_argument("-m", "--medium", action="store_const", const="medium", dest="size",
                             help="40-column portrait")
    size_group.add_argument("-b", "--big", action="store_const", const="big", dest="size",
                             help="60-column portrait")
    mode_group = parser.add_mutually_exclusive_group()
    mode_group.add_argument("-c", "--color", action="store_const", const="block", dest="mode",
                             help="truecolor with block chars (photo-like)")
    mode_group.add_argument("-a", "--ansi", action="store_const", const="ansi", dest="mode",
                             help="truecolor with ASCII chars")
    mode_group.add_argument("--no-color", action="store_const", const="mono", dest="mode",
                             help="monochrome, classic ASCII")
    parser.add_argument("-W", "--width", type=int, default=DEFAULT_WIDTH, help="text width")
    parser.add_argument("--version", action="version", version="whonews " + __version__)
    return parser.parse_args(argv)


def main(argv=None):
    """Main Parses the Args, Resolves the Character and Session, then Runs the matching whonews Command."""
    args = parse_whonews_args(argv)

    try:
        character, char = resolve_requested_character(args)
    except whosay.CharacterNotFound as e:
        print("whonews: {}".format(e), file=sys.stderr)
        return 1

    session = build_news_session(character, char, args)

    if args.signature:
        return run_signature_command(session)
    if args.anecdote is not None:
        return run_anecdote_command(session, args.anecdote or None)
    if args.history is not None:
        return run_history_command(session, args.history)

    return run_news_command(session, args)


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (BrokenPipeError, KeyboardInterrupt):
        pass
