#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
whoopinion — ask a character anything, get one sentence back in its voice.

whosay puts words in a character's mouth and whonews picks them off the
wire. This one asks: you bring the question, the character answers it as
itself.

Usage:
    whoopinion "are tabs better than spaces?"
    echo "why is the sky blue?" | whoopinion
    whoopinion -C horseshoe_crab "should I flip you over?"
    git log -1 --format=%s | whoopinion -C ozzy -b
    whoopinion --provider anthropic "is this a good idea?"

The question comes from the command line, or from stdin when the command
line has none — so a pipe works as well as an argument.

Options:
    -C, --character NAME  which character answers (default: a random one)
    --random              a random character answers (the default)
    --provider NAME   ollama, anthropic or openai
                      (default $WHONEWS_PROVIDER, else ollama: the local
                      llama-server)
    --anthropic-key K anthropic credential (default $ANTHROPIC_API_KEY)
    --anthropic-url U anthropic base url
                      (default $ANTHROPIC_BASE_URL or https://api.anthropic.com)
    --openai-key K    openai credential (default $OPENAI_API_KEY)
    --openai-url U    openai base url
                      (default $OPENAI_BASE_URL or https://api.openai.com)
    --ollama-url U    local llama-server base url
                      (default $LLAMA_HOST or http://127.0.0.1:8080)
    --model NAME      model for the chosen provider
                      (default $WHONEWS_MODEL, else the provider's own
                      default: coder-3b / claude-haiku-4-5-20251001 /
                      gpt-4o-mini)
    --timeout SEC     per-request timeout for the model (default 120)
    -t, --think       thought bubble instead of a speech bubble
    --version         print the version and exit
    plus every whosay look flag: -s/-m/-b, -c/-a/-n, -W (they live in
                      whocast.py, shared by all three scripts)

There is no cache and no archive: a question is asked once and answered
once. When the model stays silent — server down, key wrong, network out —
the character falls back to its fallback line, then to its signature
phrase, the same chain whonews walks.

The cast, the portraits and the bubble come from whocast.py. The model
backends and the flags that aim them come from whonews.py, which owns
them.

This is a parody: the answers are generated by a language model, not real
opinions from anyone.
"""
import argparse
import os
import sys

# Works when whoopinion is reached through a symlink in ~/.local/bin too.
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)))
import whocast  # noqa: E402
import whonews  # noqa: E402

__version__ = "1.0"

# Asked in both languages so the character answers in its own, whichever
# that is: the persona already fixes the language, this only fixes the shape.
OPINION_PROMPT = (
    "Responde a esta pregunta en tu propio estilo, en una sola frase.\n"
    "Answer this question in your own style, in one sentence.\n"
    "\n"
    "{}"
)


def main(argv=None):
    """Main Parses the Args,
       Asks the resolved Character the Question,
       then Prints its answer as a Panel."""
    args = parse_whoopinion_args(argv)

    question = read_question(args)
    if not question:
        print("whoopinion: no question given", file=sys.stderr)
        return 1

    try:
        character = resolve_character_choice(args)
        char = whocast.load_character(character)
        size = whocast.pick_size(args.size)
        portrait = whocast.load_character_art(character, size, whocast.pick_mode(args.mode))
    except whocast.CharacterNotFound as e:
        print("whoopinion: {}".format(e), file=sys.stderr)
        return 1

    answer = ask_character_opinion(char, question, whonews.build_model_backend(args))

    whocast.print_character_panel(answer, portrait, size, args.width, args.think)
    return 0


def parse_whoopinion_args(argv):
    """ParseWhoopinionArgs Builds the Cli parser,
       Parses argv,
       then Fills in the Provider nobody asked for."""
    parser = argparse.ArgumentParser(
        prog="whoopinion",
        description="Ask a character anything (parody).",
        epilog="example:\n"
               "  whoopinion 'are tabs better than spaces?'\n"
               "  echo 'why is the sky blue?' | whoopinion -C st_ignucius\n"
               "  whoopinion -C horseshoe_crab -b 'should I flip you over?'",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("question", nargs="*",
                        help="what to ask (reads stdin if omitted)")
    whocast.add_character_arguments(parser, "which character answers (default: a random one)")
    whonews.add_model_arguments(parser)
    whocast.add_look_arguments(parser)
    parser.add_argument("-t", "--think", action="store_true", help="thought bubble")
    parser.add_argument("--version", action="version", version="whoopinion " + __version__)

    args = parser.parse_args(argv)
    args.provider = args.provider or whonews.resolve_default_provider(args)
    return args


def read_question(args):
    """ReadQuestion Returns what to ask, from the command line or Stdin,
       or an empty string when neither carries anything."""
    text = " ".join(args.question) if args.question else sys.stdin.read()
    return " ".join(text.split())


def resolve_character_choice(args):
    """ResolveCharacterChoice Returns the named Character, or a random one,
       saying on stderr who answered when nobody named one."""
    character = whocast.pick_character(args.character, args.random)
    if character != args.character:
        print("whoopinion: character: {}".format(character), file=sys.stderr)
    return character


def ask_character_opinion(char, question, backend):
    """AskCharacterOpinion Asks the character the Question in its own voice,
       then Returns its answer, or its canned Line when the model stays silent."""
    answer = whonews.render_take_safely(
        whonews.ask_character, backend,
        char["persona"], OPINION_PROMPT.format(question), backend,
        char.get("display_name", ""), prog="whoopinion")
    return answer or resolve_canned_line(char)


def resolve_canned_line(char):
    """ResolveCannedLine Returns the character's fallback Line,
       its signature Phrase when it has no fallback,
       and an ellipsis when it has neither."""
    return char.get("fallback") or char.get("signature") or "..."


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (BrokenPipeError, KeyboardInterrupt):
        pass
